### ISSUE TITLE
Cannot enter group video chat on chrome

### ISSUE THREAD

**Issue by tommasonrhs** [AgoraIO/Agora-WordPress#74]
I am using Agora through the WordPress plugin. I am able to enter the video chat on my Desktop in any browser but on my phone, it will not let me enter when in google chrome. Is there a fix for this? @digitallysavvy

**Comment by digitallysavvy** [comment]
@tommasonrhs thanks for your interest in the Agora Video for WordPress plugin. 

Currently Agora's Web SDK _(just like all other WebRTC based video chat)_ is only available through Safari on the iPhone. This is a known limitation on iPhone, due to the camera libraries not being made available to custom WKWebKit views, only SafariWebViews allow for camera access. 

For reference:
- http://www.openradar.me/33571214 (Apple's issue tracking system)
- https://developer.apple.com/forums/thread/88052 (other Apple devs asking for this feature)
- https://stackoverflow.com/questions/39639181/add-webrtc-in-webview-in-ios (devs asking for this feature)
- https://github.com/pichillilorenzo/flutter_inappwebview/issues/200 (also causes issues for other frameworks/libraries)
